from modules.viewer.interactor_styles import AbstractInteractorStyle
from .polygon_interactorstyle import PolygonSegmentationInteractorStyle
from .rectangle_interactorstyle import RectangleSegmentationInteractorStyle