"""Radiography (X-ray) region modules for the Turbo prompt template.

GENERATED by `tools/dev/gen_turbo_xr_modules.py`. Do not hand-edit: re-run it.

Mostly AUTHORED, unlike CT and MRI. The RADIOLOGY branch of the shared prompt carries
about twenty normal-findings lines in total across four study-family blocks and has no
per-region reference, so the content comes from `tools/dev/turbo_xr_authored.py` and is
⚠️ NOT YET CLINICALLY REVIEWED. The generator cross-checks that every extracted line
still has a counterpart here.

    headings    the organ order for this region, one line
    projection  what the performed view can and cannot assess    ← X-ray only
    pathology   the descriptors worth preserving and the systems that apply here
    normal      the normal-findings reference, one line per structure
    terms       radiography dictation terms
    notes       region-specific traps

WHY `projection` EXISTS. CT and MRI acquire a volume; a radiograph acquires one view,
and a view cannot assess what it does not show. Heart size is not readable on a supine
film, free air is not excluded by a supine abdomen, the patellofemoral joint is not
assessable on AP and lateral knee views, and an AP shoulder cannot tell an anterior
from a posterior dislocation. Those are the errors this section exists to prevent.

NOT COVERED: interventional and vascular fluoroscopy — 35 of this centre's 93
fluoroscopy service codes. Bone age and barium studies are SUBTYPES, not regions: a
bone age is a study type performed on the left hand and a barium swallow is one
performed on the neck and chest.
"""

from __future__ import annotations

from typing import Dict, List

XR_MODULES: Dict[str, dict] = {
    'chest': {
        'title': 'Chest',
        'headings': 'Lungs · Pleura · Heart and mediastinum · Diaphragm · Bones · Soft tissues · Lines and tubes',
        'projection': [
            'PA erect at full inspiration is the standard. Say so, and say when the study was AP, supine or portable instead - heart size cannot be assessed on an AP or supine film, and a pneumothorax and an effusion both change appearance.',
            'Lateral adds the retrocardiac and retrosternal spaces and the posterior costophrenic recesses. Without it, do not claim a clear retrocardiac lung.',
            'A lateral decubitus distinguishes free from loculated pleural fluid. Do not call an effusion free-flowing from a frontal film alone.',
            'Expiratory films are for small pneumothorax and air trapping. Judge inspiration before calling lung volumes low.',
        ],
        'pathology': [
            'Preserve the projection he named with every finding that depends on it, particularly heart size, mediastinal width and pneumothorax.',
            'Cardiomegaly - preserve his cardiothoracic ratio or his qualitative call. The ratio is defined on a PA film, so never carry it forward from an AP or supine study he described as such.',
            'Mediastinal widening - preserve his measurement. Published thresholds run from 6 to 8 cm depending on source, so carry his number rather than a verdict.',
            'Preserve the lobe or zone he localised a consolidation, nodule or opacity to, and the silhouette sign if he used it.',
            'Pleural findings - preserve laterality, whether he called the fluid free or loculated, and any pneumothorax with its size estimate and the view it was seen on.',
            'Lines and tubes - preserve the device he named and the tip position he described, exactly. This is the finding most often acted on within minutes.',
            'Preserve any ILO pneumoconiosis classification he gave, with its profusion category and shape and size codes.',
        ],
        'normal': [
            'Both apices and costophrenic sulci are included; inspiration is adequate.',
            'Lungs are clear, without consolidation, collapse or interstitial opacity.',
            'Pulmonary vascular markings are normal in distribution and calibre.',
            'No pleural effusion, pleural thickening or pneumothorax.',
            'Cardiac silhouette is normal in size, with a cardiothoracic ratio under 50% on this PA projection.',
            'Mediastinal contours are normal and the mediastinum is not widened; the trachea is central.',
            'Both hemidiaphragms are smoothly outlined and normally positioned; no free subdiaphragmatic gas on this erect film.',
            'Bony thorax is intact; visualised ribs, clavicles and shoulder girdles show no fracture or lytic lesion.',
            'Soft tissues are unremarkable; no surgical emphysema.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['Name the projection. Heart size and mediastinal width mean different things on PA, AP and supine films.'],
    },
    'abdomen': {
        'title': 'Abdomen',
        'headings': 'Bowel gas pattern · Free intraperitoneal air · Organ outlines · Calcifications · Bones',
        'projection': [
            'Supine KUB is the baseline. Free intraperitoneal air needs an erect chest or a left lateral decubitus - never exclude free air from a supine film alone.',
            'An erect abdomen shows air-fluid levels. Their absence on a supine-only study means nothing.',
            'Say which views were performed. Obstruction, perforation and ileus are each distinguished by findings that only some projections can show.',
        ],
        'pathology': [
            'Bowel dilatation - preserve the segment he named and the calibre he measured. Published thresholds differ (small bowel >2.5 cm or >3 cm; the familiar rule uses 3 cm for small bowel, 6 cm for colon, 9 cm for caecum), so carry his figure.',
            'Obstruction - preserve his description of proximal dilatation with distal decompression, and any transition point he identified. Do not upgrade dilated loops to obstruction he did not call.',
            'Free air - preserve the view it was seen on. This is the finding where projection and conclusion are inseparable.',
            'Preserve calcifications by location and by what he attributed them to, and preserve any calculus with its side and position along the urinary tract.',
            'Preserve organ outlines and any mass effect or displaced gas pattern he described.',
            'Preserve foreign bodies and surgical hardware with their position, and any device tip he localised.',
        ],
        'normal': [
            'Bowel gas pattern is normal, with no dilated small-bowel or colonic loops.',
            'Small-bowel calibre is within normal limits and the colon is normally distended; caecal calibre is normal.',
            'No air-fluid levels to suggest obstruction on the erect projection.',
            'No free intraperitoneal gas on the erect chest or decubitus projection.',
            'No abnormal soft-tissue mass or displaced bowel to suggest mass effect.',
            'Visualised renal, hepatic and splenic outlines are within normal limits.',
            'No abnormal calcification along the renal tracts, in the gallbladder fossa or in the pelvis.',
            'Visualised lower thoracic and lumbar vertebrae, pelvis and hips show no acute bony abnormality.',
            'Soft tissues and flank stripes are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['Free intraperitoneal air cannot be excluded from a supine film.'],
    },
    'knee': {
        'title': 'Knee',
        'headings': 'Bones · Joint spaces and alignment · Patellofemoral joint · Soft tissues',
        'projection': [
            'AP and lateral are the minimum. The patellofemoral joint is not assessable on them - a congruence angle or a lateral patellofemoral angle needs a skyline, Merchant or sunrise view.',
            'Joint-space narrowing is underestimated on a non-weight-bearing AP. A flexion weight-bearing (Rosenberg) or tunnel view detects more, so do not grade tibiofemoral osteoarthritis confidently from a supine AP.',
            'A cross-table lateral is what shows lipohaemarthrosis in trauma.',
            'A negative radiograph does not exclude a Segond fracture: only 82% were visible on plain films in one ACL cohort.',
        ],
        'pathology': [
            'Preserve any Kellgren-Lawrence grade (0 to 4) with the compartment and the view it was graded on.',
            'Tibial plateau fracture - preserve the Schatzker type he assigned and note it is provisional on radiographs; preserve the depression and widening in mm as he measured them.',
            'Patellar height - preserve the ratio he used by name (Insall-Salvati, Blackburne-Peel, Caton-Deschamps) with its value. They have different normal bands, so a bare number without the method cannot be read.',
            'Preserve effusion and lipohaemarthrosis as separate findings. Lipohaemarthrosis implies an intra-articular fracture and must never be dropped.',
            'Preserve any Salter-Harris grade he gave, with the physis.',
        ],
        'normal': [
            'No fracture, and no focal lytic or sclerotic lesion.',
            'Bone mineralisation is normal for age.',
            'Medial and lateral tibiofemoral joint spaces are preserved.',
            'No marginal osteophyte, subchondral sclerosis or subchondral cyst.',
            'Patella is normally positioned with a normal patellar height ratio on the lateral projection.',
            'Patellofemoral joint space is preserved on the axial projection.',
            'Alignment is anatomical; no subluxation.',
            'No joint effusion and no lipohaemarthrosis.',
            'Soft tissues are unremarkable; no radiopaque foreign body.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'shoulder': {
        'title': 'Shoulder',
        'headings': 'Bones · Glenohumeral joint · Acromioclavicular joint · Soft tissues',
        'projection': [
            'AP alone cannot tell an anterior from a posterior dislocation. An axillary or scapular-Y view is what establishes direction - Rockwood types IV and VI in particular are not determinable from AP.',
            'Say which views were performed before describing the direction of any displacement.',
        ],
        'pathology': [
            'Proximal humeral fracture - preserve the parts he named and any Neer count. The displacement criterion is more than 1 cm or more than 45 degrees; it is his to apply, never yours.',
            'Acromioclavicular injury - preserve the Rockwood type. Its thresholds are a percentage change against the contralateral side, not an absolute measurement, so preserve the comparison he made.',
            'Dislocation - preserve the direction and the view that showed it, plus any Hill-Sachs or bony Bankart lesion he described.',
            'Preserve any AO/OTA code exactly as he gave it, with its version if he named one.',
        ],
        'normal': [
            'No fracture of the proximal humerus, clavicle or scapula.',
            'Glenohumeral joint is congruent and normally located.',
            'Acromioclavicular joint is normally aligned and the coracoclavicular relationship is symmetric with the opposite side.',
            'Subacromial space is preserved; no high-riding humeral head.',
            'No Hill-Sachs defect and no bony Bankart lesion.',
            'No calcific deposit in the rotator cuff.',
            'Bone mineralisation is normal and no focal bone lesion is seen.',
            'Visualised lung apex and ribs are unremarkable.',
            'Soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'hip': {
        'title': 'Hip',
        'headings': 'Bones · Hip joints and alignment · Pelvic ring · Soft tissues',
        'projection': [
            'An AP pelvis is what the coverage and version angles are defined on; a single hip AP does not allow comparison with the other side.',
            'A lateral or cross-table view is needed for femoral neck displacement and for posterior wall assessment.',
            'Say whether the film was weight-bearing. Joint-space assessment depends on it.',
        ],
        'pathology': [
            'Femoral neck fracture - preserve the Garden grade (I to IV) and any Pauwels type, with the displacement he described.',
            'Preserve any Tonnis osteoarthritis grade or Kellgren-Lawrence grade he assigned, and keep the system he named.',
            'Coverage angles - preserve the lateral centre-edge, Tonnis or Sharp angle he measured. Published normals disagree (LCEA normal is given as above 25 and as above 20 degrees, borderline as 20-25 or 18-25), so carry his number.',
            "Preserve Shenton's line as he described it - unbroken, or broken and on which side.",
            "Paediatric hip - preserve the acetabular index with the child's age, and preserve his statements about the Hilgenreiner and Perkin lines and the ossific nucleus.",
            'Never assign a Gustilo-Anderson grade from a radiograph. It classifies the wound at examination, not the film.',
        ],
        'normal': [
            'No fracture of the femoral neck, intertrochanteric region or pelvic ring.',
            'Femoral heads are spherical and concentrically located within the acetabula.',
            "Shenton's line is unbroken bilaterally.",
            'Hip joint spaces are preserved and symmetric.',
            'No marginal osteophyte, subchondral sclerosis or subchondral cyst.',
            'Femoral head coverage is normal; no acetabular protrusion or dysplastic configuration.',
            'Sacroiliac joints and pubic symphysis are aligned and symmetric.',
            'Bone mineralisation is normal for age.',
            'Soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'pelvis': {
        'title': 'Pelvis',
        'headings': 'Pelvic ring · Acetabula and hip joints · Sacrum and sacroiliac joints · Soft tissues',
        'projection': [
            'An AP pelvis is what the coverage and version angles are defined on; a single hip AP does not allow comparison with the other side.',
            'A lateral or cross-table view is needed for femoral neck displacement and for posterior wall assessment.',
            'Say whether the film was weight-bearing. Joint-space assessment depends on it.',
        ],
        'pathology': [
            'Femoral neck fracture - preserve the Garden grade (I to IV) and any Pauwels type, with the displacement he described.',
            'Preserve any Tonnis osteoarthritis grade or Kellgren-Lawrence grade he assigned, and keep the system he named.',
            'Coverage angles - preserve the lateral centre-edge, Tonnis or Sharp angle he measured. Published normals disagree (LCEA normal is given as above 25 and as above 20 degrees, borderline as 20-25 or 18-25), so carry his number.',
            "Preserve Shenton's line as he described it - unbroken, or broken and on which side.",
            "Paediatric hip - preserve the acetabular index with the child's age, and preserve his statements about the Hilgenreiner and Perkin lines and the ossific nucleus.",
            'Never assign a Gustilo-Anderson grade from a radiograph. It classifies the wound at examination, not the film.',
        ],
        'normal': [
            'No fracture of the femoral neck, intertrochanteric region or pelvic ring.',
            'Femoral heads are spherical and concentrically located within the acetabula.',
            "Shenton's line is unbroken bilaterally.",
            'Hip joint spaces are preserved and symmetric.',
            'No marginal osteophyte, subchondral sclerosis or subchondral cyst.',
            'Femoral head coverage is normal; no acetabular protrusion or dysplastic configuration.',
            'Sacroiliac joints and pubic symphysis are aligned and symmetric.',
            'Bone mineralisation is normal for age.',
            'Soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'elbow': {
        'title': 'Elbow',
        'headings': 'Bones · Joint and alignment · Fat pads · Soft tissues',
        'projection': [
            'A true lateral in 90 degrees of flexion is what the fat pads and the anterior humeral line depend on. An oblique or rotated lateral makes both unreadable.',
            'The AP carries the Baumann and carrying angles; the lateral carries the anterior humeral and radiocapitellar lines. Do not report a line from the view that cannot show it.',
        ],
        'pathology': [
            'A posterior fat pad is never normal. Preserve it exactly as he described it - in an adult it implies a radial head fracture, in a child a supracondylar fracture, and it is often the only sign on the film.',
            'Preserve his statement about the anterior humeral line and the radiocapitellar line - whether each bisects the capitellum, and which third.',
            'Radial head fracture - preserve any Mason type, and note whether he used the Hotchkiss modification, whose types 2 and 3 embed a functional judgement rather than a radiographic one.',
            'Supracondylar fracture - preserve the modified Gartland type. Type IV is defined by instability under fluoroscopy and cannot be assigned from a static film.',
            'Angles - preserve the Baumann or carrying angle he measured. Published normals differ widely between series, so carry his value and not a verdict.',
            'Preserve any Salter-Harris grade with the physis he named.',
        ],
        'normal': [
            'No fracture of the distal humerus, radial head, neck or olecranon.',
            'Anterior humeral line bisects the middle third of the capitellum on the lateral projection.',
            'Radiocapitellar line intersects the central capitellum in every projection.',
            'Anterior fat pad is a normal thin lucency; no posterior fat pad is visible.',
            'Elbow joint is congruent; radial head, capitellum and ulnohumeral articulation are normally aligned.',
            'Joint spaces are preserved; no marginal osteophyte or loose body.',
            'Physes, where open, are normal in width and configuration.',
            'Bone mineralisation is normal for age.',
            'Soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['A posterior fat pad is never a normal finding.'],
    },
    'wrist_hand': {
        'title': 'Wrist and hand',
        'headings': 'Bones · Carpal alignment and intervals · Joint spaces · Soft tissues',
        'projection': [
            'PA and lateral are the minimum; carpal intervals are measured on the PA and carpal alignment on a true lateral. A scaphoid view is a separate request.',
            'A normal radiograph does not exclude a scaphoid fracture. Say what was performed rather than implying the question is closed.',
        ],
        'pathology': [
            'Distal radius fracture - preserve the figures he measured: radial inclination and volar or dorsal tilt in degrees, radial height and ulnar variance in mm, and any articular step-off or gap. Linear measurements are magnification-dependent on a radiograph unless a marker was in the field, so carry his number as his.',
            'Carpal alignment - preserve the scapholunate interval he measured and any DISI or VISI he named.',
            'Scaphoid - preserve the pole he named, the displacement, and whether he called the study normal or the fracture not excluded.',
            'Preserve any Salter-Harris grade with the physis, and the fracture acuity he stated.',
            'Preserve comminution, angulation, rotation, intra-articular extension and dislocation exactly as he described them.',
        ],
        'normal': [
            'No fracture of the distal radius, ulna, carpus, metacarpals or phalanges.',
            'Radial inclination, volar tilt and radial height are within normal limits and ulnar variance is neutral.',
            'Carpal arcs are smooth and uninterrupted; carpal alignment is normal on the lateral projection.',
            'Scapholunate and lunotriquetral intervals are uniform and not widened.',
            'Distal radioulnar joint is congruent.',
            'Radiocarpal and intercarpal joint spaces are preserved.',
            'No erosion, periarticular osteopenia or chondrocalcinosis.',
            'Physes, where open, are normal in width and configuration.',
            'Soft tissues are unremarkable; no radiopaque foreign body.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'ankle_foot': {
        'title': 'Ankle and foot',
        'headings': 'Bones · Ankle mortise and hindfoot alignment · Joint spaces · Soft tissues',
        'projection': [
            'The mortise view is what shows the medial clear space and talar tilt; an AP alone does not. Say which of AP, mortise and lateral were taken.',
            'Weight-bearing changes syndesmotic and Lisfranc assessment. A supine film can miss an unstable injury that a standing film shows.',
            'Calcaneal angles are measured on the lateral; Sanders typing needs CT and cannot be assigned from a radiograph.',
        ],
        'pathology': [
            'Malleolar fracture - preserve the Weber level (A, B, C) or the Lauge-Hansen stage he named, and whether he called the syndesmosis or the mortise disrupted.',
            'Preserve any Bohler or Gissane angle he measured as his number. Both have more than one published normal range.',
            'Midfoot - preserve the Lisfranc alignment he described and any diastasis he measured, with whether the film was weight-bearing.',
            'Preserve any Salter-Harris grade with the physis he named.',
            'Preserve talar dome lesions as he described them, and do not assign an MRI or CT staging system from a radiograph.',
        ],
        'normal': [
            'No fracture of the malleoli, talus, calcaneus, midfoot or forefoot.',
            'Ankle mortise is congruent and symmetric, with a normal medial clear space and an intact syndesmosis.',
            'Talar dome is smooth, without an osteochondral defect.',
            "Bohler's angle is within normal limits on the lateral projection.",
            'Subtalar, talonavicular and calcaneocuboid joints are congruent.',
            'Tarsometatarsal alignment is preserved, without diastasis.',
            'Joint spaces are preserved; no erosion or marginal osteophyte.',
            'Physes, where open, are normal in width and configuration.',
            'Soft tissues are unremarkable; no radiopaque foreign body.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'extremity': {
        'title': 'Extremity',
        'headings': 'Bones · Joint and alignment · Soft tissues · Hardware',
        'projection': [
            'Two orthogonal views are the minimum for any fracture assessment. A single view cannot establish displacement, angulation or rotation.',
            'Say which views were performed, and include the joint above and below when he described them.',
        ],
        'pathology': [
            'Fracture - preserve the bone and part he named, the orientation, comminution, displacement, angulation, rotation, intra-articular extension, and whether he called it open.',
            'Preserve the fracture acuity he stated and any healing, callus or non-union.',
            'Preserve any Salter-Harris grade, and any AO/OTA code with its version.',
            'Preserve dislocation and its direction, and the view that showed it.',
            'Hardware - preserve the device and the specific complication he named.',
            'Linear measurements on a radiograph are magnification-dependent unless a calibration marker was in the field. Preserve his figure; do not convert it.',
        ],
        'normal': [
            'No fracture, and no focal lytic or sclerotic lesion.',
            'Bone mineralisation is normal for age.',
            'Cortices are intact and periosteum is smooth, without reaction.',
            'Alignment is anatomical; no subluxation or dislocation.',
            'Joint spaces are preserved.',
            'Physes, where open, are normal in width and configuration.',
            'No joint effusion.',
            'Soft tissues are unremarkable; no swelling, calcification or radiopaque foreign body.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['Two orthogonal views are the minimum for any fracture assessment.'],
    },
    'spine': {
        'title': 'Spine',
        'headings': 'Alignment · Vertebral bodies · Disc spaces · Posterior elements · Soft tissues',
        'projection': [
            'State the levels the film actually covered. A cervical study must show the craniocervical junction to at least the superior endplate of T1; if it did not, say so.',
            'Flexion and extension views are what establish instability, and side-bending films are what distinguish a structural from a non-structural curve. Neither can be inferred from a neutral film.',
            'A curve is called major from an upright radiograph. Do not call one major from a supine study.',
        ],
        'pathology': [
            'Vertebral fracture - preserve the level and any Genant semiquantitative grade (0, 0.5, 1, 2, 3) he assigned. The extended eSQ scale uses overlapping numbers with different meanings, so preserve which scale he used.',
            'Preserve the percentage height loss he measured and the endplate he attributed it to, and never convert his percentage into a different grade.',
            'Spondylolisthesis - preserve the level, the direction, the Meyerding grade (I to V) and any Wiltse type he named.',
            'Scoliosis - preserve the Cobb angle with the end vertebrae he used and whether the film was upright or supine. Preserve any Lenke or King classification he gave.',
            'Preserve alignment, disc-space heights and posterior element findings by level as he described them.',
            'Do not assign SLIC or AO Spine from a plain film - they are CT and MRI driven.',
        ],
        'normal': [
            'Vertebral alignment is normal, with preserved physiological curvature.',
            'Vertebral body heights are maintained; no compression or wedge deformity.',
            'Intervertebral disc spaces are preserved.',
            'Endplates are smooth and well corticated; no erosion or sclerosis.',
            'Pedicles, laminae, spinous and transverse processes are intact.',
            'Facet joints are normally aligned.',
            'No spondylolisthesis or pars defect.',
            'Bone mineralisation is normal for age.',
            'Paraspinal soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['State the levels the film covered.'],
    },
    'spine_cervical': {
        'title': 'Cervical spine',
        'headings': 'Alignment · Vertebral bodies · Disc spaces · Posterior elements · Prevertebral soft tissues · Craniocervical junction',
        'projection': [
            'State the levels the film actually covered. A cervical study must show the craniocervical junction to at least the superior endplate of T1; if it did not, say so.',
            'Flexion and extension views are what establish instability, and side-bending films are what distinguish a structural from a non-structural curve. Neither can be inferred from a neutral film.',
            'A curve is called major from an upright radiograph. Do not call one major from a supine study.',
        ],
        'pathology': [
            'Vertebral fracture - preserve the level and any Genant semiquantitative grade (0, 0.5, 1, 2, 3) he assigned. The extended eSQ scale uses overlapping numbers with different meanings, so preserve which scale he used.',
            'Preserve the percentage height loss he measured and the endplate he attributed it to, and never convert his percentage into a different grade.',
            'Spondylolisthesis - preserve the level, the direction, the Meyerding grade (I to V) and any Wiltse type he named.',
            'Scoliosis - preserve the Cobb angle with the end vertebrae he used and whether the film was upright or supine. Preserve any Lenke or King classification he gave.',
            'Preserve alignment, disc-space heights and posterior element findings by level as he described them.',
            'Do not assign SLIC or AO Spine from a plain film - they are CT and MRI driven.',
            'Prevertebral soft tissue - preserve his measurement and the level. Published thresholds disagree and all have poor sensitivity, so carry his number.',
            'Craniocervical junction - preserve the atlanto-dental interval, basion-dens interval or Powers ratio he measured. Radiographic and CT normals differ for the first two (ADI 3 mm and BDI 12 mm are radiographic figures), so preserve the modality he measured on.',
        ],
        'normal': [
            'Vertebral alignment is normal, with preserved physiological curvature.',
            'Vertebral body heights are maintained; no compression or wedge deformity.',
            'Intervertebral disc spaces are preserved.',
            'Endplates are smooth and well corticated; no erosion or sclerosis.',
            'Pedicles, laminae, spinous and transverse processes are intact.',
            'Facet joints are normally aligned.',
            'No spondylolisthesis or pars defect.',
            'Bone mineralisation is normal for age.',
            'Paraspinal soft tissues are unremarkable.',
            'The study covers the craniocervical junction to the superior endplate of T1.',
            'Prevertebral soft tissues are normal in thickness at each level.',
            'Atlanto-dental interval is within normal limits and the craniocervical junction is normally aligned.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'spine_thoracic': {
        'title': 'Thoracic spine',
        'headings': 'Alignment · Vertebral bodies · Disc spaces · Posterior elements · Paraspinal soft tissues',
        'projection': [
            'State the levels the film actually covered. A cervical study must show the craniocervical junction to at least the superior endplate of T1; if it did not, say so.',
            'Flexion and extension views are what establish instability, and side-bending films are what distinguish a structural from a non-structural curve. Neither can be inferred from a neutral film.',
            'A curve is called major from an upright radiograph. Do not call one major from a supine study.',
        ],
        'pathology': [
            'Vertebral fracture - preserve the level and any Genant semiquantitative grade (0, 0.5, 1, 2, 3) he assigned. The extended eSQ scale uses overlapping numbers with different meanings, so preserve which scale he used.',
            'Preserve the percentage height loss he measured and the endplate he attributed it to, and never convert his percentage into a different grade.',
            'Spondylolisthesis - preserve the level, the direction, the Meyerding grade (I to V) and any Wiltse type he named.',
            'Scoliosis - preserve the Cobb angle with the end vertebrae he used and whether the film was upright or supine. Preserve any Lenke or King classification he gave.',
            'Preserve alignment, disc-space heights and posterior element findings by level as he described them.',
            'Do not assign SLIC or AO Spine from a plain film - they are CT and MRI driven.',
        ],
        'normal': [
            'Vertebral alignment is normal, with preserved physiological curvature.',
            'Vertebral body heights are maintained; no compression or wedge deformity.',
            'Intervertebral disc spaces are preserved.',
            'Endplates are smooth and well corticated; no erosion or sclerosis.',
            'Pedicles, laminae, spinous and transverse processes are intact.',
            'Facet joints are normally aligned.',
            'No spondylolisthesis or pars defect.',
            'Bone mineralisation is normal for age.',
            'Paraspinal soft tissues are unremarkable.',
            'Thoracic kyphosis is within the normal range; no scoliotic curvature.',
            'Visualised lung fields and costophrenic angles are clear.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'spine_lumbar': {
        'title': 'Lumbar spine',
        'headings': 'Alignment · Vertebral bodies · Disc spaces · Posterior elements · Sacrum and sacroiliac joints',
        'projection': [
            'State the levels the film actually covered. A cervical study must show the craniocervical junction to at least the superior endplate of T1; if it did not, say so.',
            'Flexion and extension views are what establish instability, and side-bending films are what distinguish a structural from a non-structural curve. Neither can be inferred from a neutral film.',
            'A curve is called major from an upright radiograph. Do not call one major from a supine study.',
        ],
        'pathology': [
            'Vertebral fracture - preserve the level and any Genant semiquantitative grade (0, 0.5, 1, 2, 3) he assigned. The extended eSQ scale uses overlapping numbers with different meanings, so preserve which scale he used.',
            'Preserve the percentage height loss he measured and the endplate he attributed it to, and never convert his percentage into a different grade.',
            'Spondylolisthesis - preserve the level, the direction, the Meyerding grade (I to V) and any Wiltse type he named.',
            'Scoliosis - preserve the Cobb angle with the end vertebrae he used and whether the film was upright or supine. Preserve any Lenke or King classification he gave.',
            'Preserve alignment, disc-space heights and posterior element findings by level as he described them.',
            'Do not assign SLIC or AO Spine from a plain film - they are CT and MRI driven.',
        ],
        'normal': [
            'Vertebral alignment is normal, with preserved physiological curvature.',
            'Vertebral body heights are maintained; no compression or wedge deformity.',
            'Intervertebral disc spaces are preserved.',
            'Endplates are smooth and well corticated; no erosion or sclerosis.',
            'Pedicles, laminae, spinous and transverse processes are intact.',
            'Facet joints are normally aligned.',
            'No spondylolisthesis or pars defect.',
            'Bone mineralisation is normal for age.',
            'Paraspinal soft tissues are unremarkable.',
            'Lumbosacral junction is normally formed; no transitional segment.',
            'Sacroiliac joints are symmetric and unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'brain': {
        'title': 'Skull',
        'headings': 'Calvarium · Sutures and vascular grooves · Skull base · Sella · Facial bones',
        'projection': [
            'Skull radiographs answer a narrow question. They do not exclude intracranial injury, and a normal film must not be worded as though they did.',
            'Say which projections were taken. A fracture line is often visible on only one.',
        ],
        'pathology': [
            'Fracture - preserve the bone he named, whether he called it linear, depressed or diastatic, and the projection it was seen on.',
            'Preserve his distinction between a fracture line, a vascular groove and a suture. That distinction is the whole difficulty of the study and must survive rewriting.',
            'Preserve any intracranial calcification, sellar change or radiopaque foreign body with its position.',
            'Preserve his statement that a radiograph does not exclude intracranial injury if he made one.',
        ],
        'normal': [
            'Calvarium is intact, with no fracture line, depression or diastasis.',
            'Cranial sutures are normal for age and not diastatic.',
            'Vascular grooves and diploic channels follow their expected courses.',
            'Skull base and petrous temporal bones are unremarkable on the projections obtained.',
            'Sella turcica is normal in size and configuration.',
            'No abnormal intracranial calcification.',
            'No radiopaque foreign body.',
            'Visualised facial bones and paranasal sinuses are unremarkable.',
            'Soft tissues of the scalp are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'paranasal_sinuses': {
        'title': 'Paranasal sinuses',
        'headings': 'Frontal sinuses · Maxillary sinuses · Ethmoid and sphenoid · Nasal septum and turbinates · Orbital rims',
        'projection': [
            "Name every projection taken. Each sinus view profiles different sinuses and a finding belongs to the view that showed it: occipitomental (Water's) for the maxillary antra and the orbital floors, occipitofrontal (Caldwell) for the frontal and ethmoid sinuses, lateral for the sphenoid and the posterior wall of the frontal sinus and the nasopharyngeal airway, submentovertex for the sphenoid and the posterior ethmoids.",
            'An air-fluid level requires an ERECT film. A supine study cannot show one, and its absence on a supine film means nothing.',
            'The ethmoid and sphenoid sinuses are poorly assessed on plain films at all. Preserve any statement he made to that effect and any recommendation for CT.',
        ],
        'pathology': [
            'Preserve which sinus, which side, and whether he described mucosal thickening, an air-fluid level or complete opacification. These are different findings.',
            'Preserve the projection with any air-fluid level, and whether the film was erect.',
            'Preserve nasal septal deviation and turbinate hypertrophy as he described them.',
            'Preserve any fracture of the orbital rim, nasal bones or sinus wall with the side.',
        ],
        'normal': [
            'Frontal sinuses are aerated and symmetric.',
            'Maxillary antra are aerated, with no mucosal thickening and no air-fluid level on this erect projection.',
            'Visualised ethmoid air cells are clear.',
            'Sphenoid sinus is aerated as far as this projection allows.',
            'Nasal septum is midline and the turbinates are normal in size.',
            'Orbital rims and floors are intact.',
            'Zygomatic arches and the visualised facial buttresses are continuous.',
            'No radiopaque foreign body.',
            'Soft tissues are unremarkable.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'dental_maxillofacial': {
        'title': 'Maxillofacial and dental',
        'headings': 'Dentition · Mandible · Maxilla and alveolar ridges · Temporomandibular joints · Maxillary sinuses · Facial buttresses',
        'projection': [
            'A panoramic view surveys the dentition and mandible but distorts and superimposes; it cannot substitute for a periapical or an occlusal view for a single tooth.',
            'Facial trauma needs at least an occipitomental and a lateral. Say which were taken.',
        ],
        'pathology': [
            'Preserve tooth identity exactly as he gave it, in the notation he used. Renumbering a tooth changes which one gets treated.',
            'Preserve periapical, periodontal and caries findings by tooth, and any impaction with the angulation he described.',
            'Mandibular fracture - preserve the site he named (condyle, ramus, angle, body, parasymphysis, symphysis, coronoid, alveolus), whether unifocal or multifocal, and any tooth in the fracture line. Mandibular fractures are frequently bilateral - preserve both sides if he described both.',
            'Preserve temporomandibular joint position and any condylar dislocation.',
            'Preserve anything he said about dental occlusion, even where he called the misalignment minimal.',
        ],
        'normal': [
            'Dentition is complete for age, with normal crown and root morphology.',
            'No carious lesion, periapical lucency or retained root.',
            'Alveolar bone height is normal, with no periodontal bone loss.',
            'Mandible is intact throughout, including both condyles, rami, angles, body and symphysis.',
            'Maxilla and alveolar ridges are intact.',
            'Temporomandibular joints are normally located, with condyles seated in the glenoid fossae.',
            'Visualised maxillary antra are aerated.',
            'No impacted or supernumerary tooth.',
            'No radiopaque foreign body and no soft-tissue calcification.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'head_neck': {
        'title': 'Neck',
        'headings': 'Airway and soft tissues · Cervical spine alignment · Bony structures · Calcifications',
        'projection': [
            'A lateral soft-tissue neck is taken in inspiration with the neck extended. A flexed or expiratory film exaggerates the prevertebral soft tissues and the retropharyngeal space, and must not be read as though it did not.',
        ],
        'pathology': [
            'Preserve airway calibre and any narrowing he described, with the level.',
            'Preserve prevertebral and retropharyngeal soft tissue thickness as his measurement, with the level and the phase of respiration if he gave it.',
            'Preserve any radiopaque foreign body with its position and orientation, and whether he localised it to the airway or the oesophagus.',
            'Preserve calcifications and any tracheal deviation with its direction.',
        ],
        'normal': [
            'Airway is patent and normal in calibre throughout.',
            'Prevertebral and retropharyngeal soft tissues are normal in thickness on this extended inspiratory lateral projection.',
            'Epiglottis and aryepiglottic folds are normal in contour.',
            'Trachea is central and normal in calibre.',
            'Visualised cervical vertebrae show normal alignment and preserved disc spaces.',
            'No radiopaque foreign body in the airway or the cervical oesophagus.',
            'No soft-tissue calcification and no free gas in the soft tissues.',
            'Visualised lung apices are clear.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': [],
    },
    'bone_density': {
        'title': 'Bone densitometry',
        'headings': 'Lumbar spine · Total hip and femoral neck · Forearm when indicated · Vertebral fracture assessment',
        'projection': [
            'State the sites scanned and the regions of interest. The diagnosis is assigned from the lowest T-score across lumbar spine, total hip, femoral neck or 33% radius - not per site.',
            'State the instrument manufacturer and model. Values are not comparable across machines, and a follow-up study on a different scanner cannot be compared to the prior.',
            'State any vertebra excluded and why. A vertebra may be excluded if it is clearly abnormal, or if it differs by more than 1.0 T-score from its neighbours.',
            'For bilateral hips, diagnosis uses the lowest of the four femoral neck and total hip values, never the mean. Monitoring uses the mean bilateral total hip.',
        ],
        'pathology': [
            'Preserve every BMD value in g/cm² with its site, and every T-score and Z-score with the site it belongs to.',
            'Preserve the diagnostic category he assigned and never derive one he did not state. One category is assigned per patient, from the lowest T-score.',
            'Preserve whether he reported T-scores or Z-scores. Z-scores are what apply before menopause, in men under 50, and in children - and in children a T-score must not appear at all, nor the words osteopenia or osteoporosis.',
            'Preserve any fracture-risk calculation with the tool he named and the inputs he listed.',
            'Preserve any vertebral fracture assessment finding with its level and grade, and any prior-study comparison with the least significant change he applied.',
            'Preserve his statement when a non-central device was used - the WHO classification does not apply to those T-scores, and that caveat must not be dropped.',
        ],
        'normal': [
            'Lumbar spine L1 to L4: bone mineral density and T-score within the expected range for the reference population.',
            'Total hip and femoral neck: bone mineral density and T-score within the expected range.',
            'Diagnostic category assigned from the lowest T-score across the sites measured.',
            'All vertebrae assessable; none excluded for structural abnormality or for a T-score differing by more than 1.0 from its neighbours.',
            'No focal skeletal abnormality within the regions of interest.',
            'Trabecular and cortical pattern are normal.',
            'Instrument manufacturer and model recorded; positioning and analysis satisfactory.',
            'No prior study available for comparison, or change within the least significant change for this instrument.',
        ],
        'terms': ['رادیوگرافی → radiograph', 'گرافی → radiograph', 'نمای رخ → frontal (AP/PA) projection', 'نمای نیمرخ → lateral projection', 'ایستاده → erect', 'خوابیده → supine', 'شکستگی → fracture', 'دررفتگی → dislocation', 'استئوپروز → osteoporosis', 'اسکولیوز → scoliosis', 'افیوژن → effusion', 'کنسولیداسیون → consolidation', 'باریم → barium', 'ماده حاجب → contrast medium'],
        'notes': ['One diagnostic category per patient, from the lowest T-score - not one per site.'],
    },
}


#: Study types. Radiography has more of them than any other modality: a
#: hysterosalpingogram, a barium enema and a colon transit study are all
#: abdominopelvic and share nothing else.
XR_SUBTYPE_PACKAGES: Dict[str, dict] = {
    'xr_hsg': {
        'title': 'Hysterosalpingography',
        'technique': [
            'Preserve the phase of the cycle and any statement about pregnancy exclusion.',
            'Preserve the contrast agent, the volume used, and whether he described the injection as difficult, refluxing or painful - each qualifies the images.',
        ],
        'must_report': [
            'Preserve the uterine cavity contour as he described it - size, shape, any filling defect, synechiae or septum - and any uterine anomaly classification he named, with the system.',
            'Preserve each tube separately by side: whether it filled, its course and calibre, and whether free peritoneal spill was seen. A tube that did not fill and a tube that is occluded are different statements.',
            'Preserve the spill as he described it - free, loculated, or absent - and the side.',
            'Preserve any intravasation of contrast into the myometrium or venous channels.',
        ],
        'pathology': [
            'Never conclude tubal occlusion from a tube that failed to fill on one attempt. Preserve his wording, including any note of spasm or a repeat injection.',
            'Preserve any recommendation for laparoscopy, repeat study or antibiotic cover.',
        ],
    },
    'xr_rug': {
        'title': 'Retrograde urethrography and voiding cystourethrography',
        'technique': [
            'Preserve which study was performed - retrograde, voiding, or both - and the catheter or technique used. A retrograde study shows the anterior urethra and a voiding study the posterior urethra and bladder neck; they answer different questions and one does not substitute for the other.',
            'Preserve the obliquity used. A urethra assessed on a straight AP is foreshortened.',
        ],
        'must_report': [
            'Preserve each urethral segment by name - penile, bulbar, membranous, prostatic - and the calibre and appearance of each.',
            'Stricture - preserve the segment, the length in centimetres, the residual calibre, and whether he described it as single or multiple.',
            'Preserve bladder capacity, contour and any diverticulum or trabeculation.',
            'Preserve vesicoureteric reflux by side and by the grade he assigned, with the grading system named. Never assign a grade he did not state.',
            'Preserve any extravasation, false passage, fistula or contrast in the periurethral tissues.',
        ],
        'pathology': [
            'Preserve post-void residual if he reported one, with how it was assessed.',
            'Preserve any statement that a segment was not distended or not assessed.',
        ],
    },
    'xr_ivp': {
        'title': 'Intravenous pyelography / urography',
        'technique': [
            'Preserve the contrast agent, the dose and every timed film he described. The phases - nephrogram, pyelogram, delayed - answer different questions and a finding belongs to the phase it was seen in.',
            'Preserve any preliminary control film and what it showed. A calculus visible only on the control film is obscured once contrast is given.',
            'Preserve any compression, prone or post-void film, and any delayed film with its timing.',
            'Preserve any statement about renal function or non-excretion - a kidney that did not excrete is the central finding of the study, not an omission.',
        ],
        'must_report': [
            'Preserve each kidney separately: position, axis, size, contour and the timing and symmetry of its nephrogram.',
            'Preserve the pelvicalyceal system on each side - calyceal architecture, any blunting, clubbing or dilatation - and the level of any obstruction.',
            'Preserve ureteric course, calibre and any filling defect or deviation, by side and by segment.',
            'Preserve the bladder outline, any filling defect, and the post-void appearance.',
        ],
        'pathology': [
            'Preserve any filling defect exactly as characterised, and never convert a filling defect into a diagnosis he did not give.',
            "Preserve the study's stated limitation. Urography assesses the collecting system and excretion, not renal parenchymal lesions, and any such caveat he made must survive.",
        ],
    },
    'xr_barium_swallow': {
        'title': 'Barium swallow and oesophagram',
        'technique': [
            'Preserve the contrast used and whether the study was single- or double-contrast. Double contrast shows mucosal detail; single contrast shows distensibility, strictures and motility better. Preserve which was performed.',
            'Preserve the positions and phases he screened - erect, prone oblique, supine, Trendelenburg - and any water-siphon or provocative manoeuvre.',
            'Preserve any use of a barium tablet or marshmallow for a suspected stricture.',
        ],
        'must_report': [
            'Preserve the swallowing phases he assessed, and any penetration or aspiration with the consistency it occurred on and any scale he applied.',
            'Preserve pharyngeal findings separately from oesophageal ones - pooling, residue, cricopharyngeal bar, pouch.',
            'Preserve oesophageal motility as he described it - primary and secondary peristalsis, tertiary contractions - since motility is only assessable fluoroscopically.',
            'Preserve any stricture with its level, length and calibre, and any mucosal abnormality, ulcer, ring or web.',
            'Preserve hiatus hernia with its type and size, and reflux with the manoeuvre that provoked it.',
        ],
        'pathology': [
            'Preserve his wording on aspiration exactly. Silent aspiration and aspiration with cough are different findings, and any recommendation for a speech and language assessment must survive.',
            'Preserve any suspected perforation or leak and the contrast agent used, since a suspected perforation changes which agent is safe.',
        ],
    },
    'xr_barium_meal': {
        'title': 'Barium meal and upper gastrointestinal study',
        'technique': [
            'Preserve whether the study was single- or double-contrast and whether an effervescent agent and a hypotonic drug were given. Mucosal relief depends on both.',
            'Preserve the fasting state and the positions screened.',
        ],
        'must_report': [
            'Preserve the oesophagus, stomach and duodenum as separate sections.',
            'Preserve gastric distensibility, rugal pattern, and any ulcer with its site, size and whether he called it benign or malignant in appearance.',
            'Preserve any filling defect, mass or rigid segment with its location.',
            'Preserve the duodenal cap and loop, and any deformity, diverticulum or extrinsic impression.',
            'Preserve gastric emptying and any delay he observed.',
        ],
        'pathology': [
            'Preserve his characterisation of an ulcer exactly. Benign and malignant features are his call from the fluoroscopic appearance and must not be softened or upgraded.',
            'Preserve any recommendation for endoscopy.',
        ],
    },
    'xr_sbft': {
        'title': 'Small-bowel follow-through and enteroclysis',
        'technique': [
            'Preserve whether this was a follow-through or an enteroclysis via a nasojejunal tube - they have different sensitivity and different distension.',
            'Preserve the timing of each film and the total transit time to the caecum.',
            'Preserve any compression or spot views of the terminal ileum, which is the segment the study most often exists to answer.',
        ],
        'must_report': [
            'Preserve small-bowel calibre, fold pattern and distribution as he described them, by segment.',
            'Preserve the terminal ileum specifically - calibre, fold thickening, ulceration, stricture, separation of loops.',
            'Preserve any stricture with its length and the degree of narrowing, and any proximal dilatation.',
            'Preserve fistula, sinus tract or abscess cavity with its course.',
            'Preserve transit time and any statement of delay.',
        ],
        'pathology': [
            'Preserve his distinction between a fixed narrowing and a transient contraction - only the fluoroscopist can make it, and it is lost if the wording is generalised.',
            'Preserve any recommendation for cross-sectional enterography.',
        ],
    },
    'xr_barium_enema': {
        'title': 'Barium enema',
        'technique': [
            'Preserve whether the study was single- or double-contrast. Double contrast shows mucosal detail and small polyps; single contrast is better for obstruction, fistula and in the frail or unprepared patient. Preserve which was performed and why if he said.',
            'Preserve the bowel preparation and its adequacy. Residual faecal material limits the study and any such statement qualifies everything after it.',
            'Preserve any water-soluble agent used instead of barium, and the reason - suspected perforation or a planned surgery changes the agent.',
            'Preserve whether the caecum was reached and refluxed into the terminal ileum.',
        ],
        'must_report': [
            'Preserve each colonic segment by name - rectum, sigmoid, descending, splenic flexure, transverse, hepatic flexure, ascending, caecum.',
            'Preserve any filling defect with its segment, size and morphology, and whether he called it sessile or pedunculated.',
            'Preserve strictures with segment, length and shoulder morphology, and any proximal dilatation.',
            'Preserve diverticular disease with its distribution and severity.',
            'Preserve mucosal abnormality, haustral loss and any fistula or extravasation.',
        ],
        'pathology': [
            'Preserve his statement about segments that were not adequately distended or coated. On an enema, a poorly seen segment is a reported limitation.',
            'Preserve any recommendation for colonoscopy or CT colonography.',
        ],
    },
    'xr_fistulography': {
        'title': 'Fistulography',
        'technique': [
            'Preserve the external opening he catheterised, its site, and the contrast volume and injection pressure he described.',
            'Preserve the projections used and any statement that the tract was not fully opacified - an unopacified branch is not an absent branch.',
        ],
        'must_report': [
            "Preserve the tract's course, length and calibre, and every branch or secondary tract he demonstrated.",
            'Preserve the internal opening if he identified one, with its position, and say so if he did not.',
            'Preserve the relationship of the tract to any named structure - for a perianal fistula, to the internal and external sphincters, the levator plate and the ischiorectal fossa.',
            'Preserve any Parks classification he assigned, with the type. Never assign a type he did not state - Parks is defined by the relationship to the sphincter complex and a fistulogram may not show it.',
            'Preserve any abscess cavity, communication with bowel, bladder or skin, and any extravasation.',
        ],
        'pathology': [
            'Preserve the anatomical region. Fistulography is performed at many sites and a tract described without its region is not actionable.',
            'Preserve any recommendation for MRI, which resolves the sphincter relationship that a fistulogram often cannot.',
        ],
    },
    'xr_colon_transit': {
        'title': 'Colon transit time with radiopaque markers',
        'technique': [
            'Preserve the protocol by name and its parameters: how many markers, how many capsules, on which days, and on which day the film was taken. At least four protocols are in use - single-capsule day 5, Metcalf, Arhan, Chaussade - with different marker counts, different film days and different thresholds. A marker count means nothing without the protocol it belongs to and must never be read against a different one.',
            'Preserve any laxative, enema or medication he recorded as withheld or taken during the study period.',
        ],
        'must_report': [
            'Preserve the total number of markers retained, and the number in each colonic segment - right colon, left colon, rectosigmoid - as he counted them.',
            'Preserve the segmental landmarks he used, if he stated them. The segments are defined by lines drawn on the film and different sources draw them differently.',
            'Preserve any transit time in hours he calculated, together with the formula or protocol it came from.',
            'Preserve the distribution pattern as he described it - scattered throughout the colon, or accumulated in the rectosigmoid. That pattern is the interpretation, not the count.',
            'Preserve the number and dates of all films if the study ran over several days.',
        ],
        'pathology': [
            'Never convert a retained-marker count into a diagnosis. Slow-transit constipation and a defecation disorder are distinguished by the distribution and by thresholds that are protocol-specific, and the published cut-offs disagree.',
            'Preserve his conclusion in his words - normal transit, slow transit, outlet obstruction, or inconclusive - and any recommendation for anorectal manometry, a defecography or a repeat study at a longer interval.',
        ],
    },
    'xr_limb_alignment': {
        'title': 'Standing lower-limb alignment (long-leg film)',
        'technique': [
            'Preserve that the film was weight-bearing and full-length from hip to ankle, and preserve the patellar position - the patellae must face forward, because limb rotation alters the measured angles substantially.',
            'Preserve whether a calibration marker or ruler was in the field. Every length in millimetres is magnification-dependent without one; the angles are not.',
            'Preserve any statement of fixed flexion at the knee, which invalidates the coronal measurement.',
            'Preserve what the film cannot answer - it is a coronal study and says nothing about sagittal deformity or torsion.',
        ],
        'must_report': [
            'Preserve each angle he measured, by its abbreviation, with its value and side: hip-knee-ankle angle, mechanical axis deviation, mechanical lateral distal femoral angle, medial proximal tibial angle, lateral distal tibial angle, joint line convergence angle, medial proximal femoral angle.',
            'Preserve whether he reported the mechanical or the anatomical tibiofemoral angle, and any anatomical-mechanical offset he applied. They differ by several degrees and are not interchangeable.',
            'Preserve the mechanical axis deviation with its direction, medial or lateral, and in millimetres.',
            'Preserve femoral and tibial segment lengths and any limb-length discrepancy, with the side that is shorter and the calibration method.',
            'Preserve his statement of where the deformity is - femoral, tibial, both, or intra-articular - since that is what the joint angles exist to localise.',
        ],
        'pathology': [
            'Preserve every value as his. Published normals for these angles disagree between sources - mechanical axis deviation alone is given as 4 plus or minus 2 mm medial, as 8 plus or minus 7 mm medial, and as 3 mm either side - and the joint angles are published both as a mean with a tolerance and as asymmetric ranges. Never restate his figure against a different reference or convert it into a verdict.',
            'Preserve his terms for the deformity - genu varum, genu valgum - only where he used them, and never derive one from an angle he reported.',
            'Preserve any planned correction, osteotomy level or surgical recommendation.',
        ],
    },
    'xr_spine_alignment': {
        'title': 'Total spine and alignment views',
        'technique': [
            'Preserve that the film was upright and full-length, and preserve whether it was taken PA or AP, since the projection changes both dose and apparent rotation.',
            'Preserve any statement that a curve was measured on a supine film. A curve is called major only from an upright radiograph.',
            'Preserve whether the study included the femoral heads, which the sagittal parameters depend on.',
        ],
        'must_report': [
            'Preserve every Cobb angle with the end vertebrae he selected, the direction of convexity and the region of the curve. A Cobb angle without its end vertebrae cannot be reproduced on the next study.',
            'Preserve the apex of each curve and whether he called a curve structural or compensatory.',
            'Preserve coronal and sagittal balance measurements with the plumb line he used.',
            'Preserve sagittal parameters by name where he gave them - thoracic kyphosis, lumbar lordosis, pelvic incidence, pelvic tilt, sacral slope - with the levels.',
            'Preserve vertebral rotation and any method he named for grading it, and shoulder or pelvic obliquity.',
            'Preserve skeletal maturity if he assessed it, with the index used.',
        ],
        'pathology': [
            'Preserve any comparison with a prior study, including the interval and the prior values. On an alignment film, progression is the finding.',
            'Preserve any Lenke or King classification only if he assigned one.',
        ],
    },
    'xr_spine_flexion_extension': {
        'title': 'Flexion and extension views',
        'technique': [
            'Preserve that both a flexion and an extension film were obtained, and preserve any statement that the range achieved was limited by pain or guarding - an inadequate excursion cannot exclude instability and that caveat must survive.',
            'Preserve whether the films were upright or supine and whether they were physician-supervised.',
        ],
        'must_report': [
            'Preserve translation in millimetres and angulation in degrees at each level, measured between the two films, and the method he used.',
            'Preserve which level or levels he assessed, and preserve any level he could not assess.',
            'Preserve the position of any listhesis on each film separately - a slip that reduces on extension is a different finding from a fixed one.',
            'Preserve any hardware and its position on both films.',
        ],
        'pathology': [
            'Preserve his conclusion about instability in his words. Published millimetre and degree criteria vary and this study exists to answer that question, so never derive the conclusion from the measurements yourself.',
            'Preserve any statement that the study was non-diagnostic.',
        ],
    },
    'xr_spine_oblique': {
        'title': 'Oblique spine views',
        'technique': [
            'Preserve that oblique views were obtained and the side of each, since the oblique shows the pars and the facets on the side towards or away from the film depending on the projection.',
            'Preserve the region examined.',
        ],
        'must_report': [
            'Preserve the pars interarticularis on each side at each level examined, and any defect with its level and side.',
            'Preserve the facet joints and the neural foramina as he described them, by level and side.',
            'Preserve any statement that a level was obscured or not adequately profiled.',
        ],
        'pathology': [
            'Preserve his wording about a suspected pars defect. Preserve any recommendation for CT or SPECT, which is what resolves an equivocal oblique.',
        ],
    },
    'xr_bone_age': {
        'title': 'Bone age',
        'technique': [
            'Preserve which hand was radiographed - the left is conventional - and the projection.',
            'Preserve the method he used by name. Greulich-Pyle reads the film against an atlas of standards; Tanner-Whitehouse scores individual bones and sums them. They produce different numbers from the same film and are not interchangeable, so a bone age without its method cannot be compared with a previous one.',
        ],
        'must_report': [
            'Preserve the chronological age, with the date of birth or the age in years and months as he gave it.',
            'Preserve the assessed skeletal age with the method, and any standard deviation or range he quoted with it.',
            'Preserve his comparison between the two - advanced, delayed, or concordant - and the magnitude of any difference.',
            'Preserve the specific epiphyses and carpal ossification centres he based the assessment on, if he named them.',
            'Preserve the sex used for the reference standard. The atlas standards are sex-specific and a bone age read against the wrong standard is wrong.',
        ],
        'pathology': [
            'Never compute a skeletal age, a percentile or a predicted adult height from the findings. Each depends on the method and its reference population.',
            'Preserve any incidental skeletal finding on the hand film separately.',
            'Preserve any recommendation for endocrine referral or interval reassessment.',
        ],
    },
    'xr_skeletal_survey': {
        'title': 'Skeletal survey / bone survey',
        'technique': [
            'Preserve the indication, because the projection list differs by indication - myeloma, metastatic disease, suspected physical abuse in a child, and skeletal dysplasia are four different protocols.',
            'Preserve the complete list of projections actually obtained, and any region that was not imaged. A survey is defined by its coverage, and an unimaged region is a reported limitation, not a normal one.',
            'Preserve any statement he made about the sensitivity of radiography for the indication, and any recommendation for whole-body low-dose CT, MRI or bone scintigraphy - for myeloma in particular, current guidance has moved away from the radiographic survey as first-line.',
        ],
        'must_report': [
            'Preserve findings region by region, in the order he surveyed - skull, spine, thorax and ribs, pelvis, and each long bone by side.',
            'Preserve every lesion with its bone, its position within the bone, its size, and whether he called it lytic, sclerotic or mixed.',
            'Preserve any pathological fracture, cortical breach, periosteal reaction or soft tissue component.',
            'Preserve the overall bone mineralisation and any diffuse abnormality.',
            'Preserve explicitly that a region was normal where he said so - on a survey, a normal region is a positive statement of coverage.',
        ],
        'pathology': [
            'In a suspected-abuse survey, preserve every fracture with its age or stage of healing exactly as he described it, and preserve any statement about the number of fractures and whether they are of different ages. Never estimate or harmonise fracture ages.',
            'Preserve any recommendation for a follow-up survey at an interval, which is part of the standard protocol in suspected abuse.',
            'Preserve any comparison with a prior survey, including which lesions are new.',
        ],
    },
    'xr_nasal_bone': {
        'title': 'Nasal bone radiography',
        'technique': [
            'Preserve the projections obtained - a lateral soft-tissue nasal view and, where taken, an occipitomental or a superoinferior axial. A nasal fracture is often visible on only one.',
            'Preserve any statement that the study does not exclude a nasal fracture and that the diagnosis is clinical. That caveat is the most important sentence in this report and must not be dropped.',
            'Preserve any soft-tissue swelling that limited the assessment.',
        ],
        'must_report': [
            'Preserve the nasal bones and the frontal process of the maxilla as separate structures.',
            'Preserve any fracture with its side, whether he called it displaced or undisplaced, and the direction of any displacement.',
            'Preserve the nasal septum and any deviation or fracture.',
            'Preserve the anterior nasal spine and the visualised frontal sinuses.',
            'Preserve any radiolucent line he explicitly identified as a normal suture or vascular groove rather than a fracture. That distinction is the whole difficulty of this study.',
        ],
        'pathology': [
            'Preserve his wording on displacement, since it determines whether reduction is offered.',
            'Preserve any suspicion of a wider facial injury and any recommendation for CT.',
        ],
    },
    'xr_shoulder_special': {
        'title': 'Specialised shoulder projections',
        'technique': [
            'Preserve every projection by name - axillary, Grashey or true AP, scapular-Y, Stryker notch, West Point, Garth, outlet - because each exists to answer one question and a finding must be attributed to the view that shows it.',
            'An AP alone cannot establish the direction of a dislocation. Preserve his statement of which view demonstrated it.',
            'Preserve any view that was attempted and not obtained because of pain.',
        ],
        'must_report': [
            'Preserve the glenohumeral relationship as seen on the axillary or scapular-Y, and the true joint space as seen on the Grashey view.',
            'Preserve any Hill-Sachs or bony Bankart lesion with the view it was seen on.',
            'Preserve the acromial morphology and the subacromial space where an outlet view was taken.',
            'Preserve the acromioclavicular joint and any comparison with the opposite side.',
        ],
        'pathology': [
            'Preserve the direction of any dislocation and the view that established it.',
            'Preserve any recommendation for CT or MR arthrography for bone loss quantification.',
        ],
    },
    'xr_mastoid': {
        'title': 'Mastoid and petrous temporal projections',
        'technique': [
            'Preserve every projection by name - Schuller, Law, Stenvers, Towne - and the side. Each profiles a different part of the temporal bone and a finding belongs to the view that showed it.',
            'Preserve any statement that plain films do not exclude temporal bone pathology and that CT is the modality of choice. Preserve any recommendation that follows.',
        ],
        'must_report': [
            'Preserve the degree of mastoid pneumatisation on each side and any comparison between them.',
            'Preserve the clarity of the air cells, any loss of trabeculation, and any sclerosis or coalescence.',
            'Preserve the sinodural angle and the sigmoid sinus plate where he described them.',
            'Preserve the internal auditory canal and petrous apex where a Stenvers or Towne view was taken.',
        ],
        'pathology': [
            'Preserve the side with every finding.',
            'Preserve his distinction between under-pneumatisation and opacification - they are different findings with different meanings.',
        ],
    },
}
