# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dicom_service_pb2 as dicom__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dicom_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DicomServiceStub(object):
    """--- Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetThumbnails = channel.unary_unary(
                '/dicomservice.DicomService/GetThumbnails',
                request_serializer=dicom__service__pb2.ThumbnailRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.ThumbnailResponse.FromString,
                _registered_method=True)
        self.GetDicomImages = channel.unary_stream(
                '/dicomservice.DicomService/GetDicomImages',
                request_serializer=dicom__service__pb2.DicomImageRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.DicomImageInfo.FromString,
                _registered_method=True)
        self.QuerySeriesThumbnails = channel.unary_unary(
                '/dicomservice.DicomService/QuerySeriesThumbnails',
                request_serializer=dicom__service__pb2.SeriesQueryRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.SeriesQueryResponse.FromString,
                _registered_method=True)
        self.GetSeriesThumbnail = channel.unary_unary(
                '/dicomservice.DicomService/GetSeriesThumbnail',
                request_serializer=dicom__service__pb2.SingleThumbnailRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.SeriesThumbnailResponse.FromString,
                _registered_method=True)
        self.StreamSeriesThumbnails = channel.unary_stream(
                '/dicomservice.DicomService/StreamSeriesThumbnails',
                request_serializer=dicom__service__pb2.SeriesQueryRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.SeriesThumbnailResponse.FromString,
                _registered_method=True)
        self.GetStudyThumbnails = channel.unary_unary(
                '/dicomservice.DicomService/GetStudyThumbnails',
                request_serializer=dicom__service__pb2.StudyThumbnailsRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.StudyThumbnailsResponse.FromString,
                _registered_method=True)
        self.GetStudyDicomFiles = channel.unary_unary(
                '/dicomservice.DicomService/GetStudyDicomFiles',
                request_serializer=dicom__service__pb2.StudyDicomRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.StudyDicomResponse.FromString,
                _registered_method=True)
        self.StreamStudyDicomFiles = channel.unary_stream(
                '/dicomservice.DicomService/StreamStudyDicomFiles',
                request_serializer=dicom__service__pb2.StudyDicomRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.DicomInstanceResponse.FromString,
                _registered_method=True)
        self.GetPatientList = channel.unary_unary(
                '/dicomservice.DicomService/GetPatientList',
                request_serializer=dicom__service__pb2.PatientListRequest.SerializeToString,
                response_deserializer=dicom__service__pb2.PatientListResponse.FromString,
                _registered_method=True)


class DicomServiceServicer(object):
    """--- Service Definition ---

    """

    def GetThumbnails(self, request, context):
        """Fetches study info and series thumbnails (legacy method)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDicomImages(self, request, context):
        """Fetches individual DICOM images for a series as a stream
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySeriesThumbnails(self, request, context):
        """NEW THUMBNAIL ENDPOINTS:

        Query series with optional filters and get thumbnails
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeriesThumbnail(self, request, context):
        """Get thumbnail for a specific series
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSeriesThumbnails(self, request, context):
        """Stream thumbnails for large result sets
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudyThumbnails(self, request, context):
        """Get all thumbnails for a specific study
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStudyDicomFiles(self, request, context):
        """Get all DICOM files for a specific study
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStudyDicomFiles(self, request, context):
        """Stream DICOM files for a specific study (for large datasets)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPatientList(self, request, context):
        """Get patient list with filtering and pagination
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DicomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetThumbnails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetThumbnails,
                    request_deserializer=dicom__service__pb2.ThumbnailRequest.FromString,
                    response_serializer=dicom__service__pb2.ThumbnailResponse.SerializeToString,
            ),
            'GetDicomImages': grpc.unary_stream_rpc_method_handler(
                    servicer.GetDicomImages,
                    request_deserializer=dicom__service__pb2.DicomImageRequest.FromString,
                    response_serializer=dicom__service__pb2.DicomImageInfo.SerializeToString,
            ),
            'QuerySeriesThumbnails': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySeriesThumbnails,
                    request_deserializer=dicom__service__pb2.SeriesQueryRequest.FromString,
                    response_serializer=dicom__service__pb2.SeriesQueryResponse.SerializeToString,
            ),
            'GetSeriesThumbnail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeriesThumbnail,
                    request_deserializer=dicom__service__pb2.SingleThumbnailRequest.FromString,
                    response_serializer=dicom__service__pb2.SeriesThumbnailResponse.SerializeToString,
            ),
            'StreamSeriesThumbnails': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSeriesThumbnails,
                    request_deserializer=dicom__service__pb2.SeriesQueryRequest.FromString,
                    response_serializer=dicom__service__pb2.SeriesThumbnailResponse.SerializeToString,
            ),
            'GetStudyThumbnails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudyThumbnails,
                    request_deserializer=dicom__service__pb2.StudyThumbnailsRequest.FromString,
                    response_serializer=dicom__service__pb2.StudyThumbnailsResponse.SerializeToString,
            ),
            'GetStudyDicomFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStudyDicomFiles,
                    request_deserializer=dicom__service__pb2.StudyDicomRequest.FromString,
                    response_serializer=dicom__service__pb2.StudyDicomResponse.SerializeToString,
            ),
            'StreamStudyDicomFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStudyDicomFiles,
                    request_deserializer=dicom__service__pb2.StudyDicomRequest.FromString,
                    response_serializer=dicom__service__pb2.DicomInstanceResponse.SerializeToString,
            ),
            'GetPatientList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPatientList,
                    request_deserializer=dicom__service__pb2.PatientListRequest.FromString,
                    response_serializer=dicom__service__pb2.PatientListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dicomservice.DicomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dicomservice.DicomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DicomService(object):
    """--- Service Definition ---

    """

    @staticmethod
    def GetThumbnails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/GetThumbnails',
            dicom__service__pb2.ThumbnailRequest.SerializeToString,
            dicom__service__pb2.ThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDicomImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dicomservice.DicomService/GetDicomImages',
            dicom__service__pb2.DicomImageRequest.SerializeToString,
            dicom__service__pb2.DicomImageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySeriesThumbnails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/QuerySeriesThumbnails',
            dicom__service__pb2.SeriesQueryRequest.SerializeToString,
            dicom__service__pb2.SeriesQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeriesThumbnail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/GetSeriesThumbnail',
            dicom__service__pb2.SingleThumbnailRequest.SerializeToString,
            dicom__service__pb2.SeriesThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSeriesThumbnails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dicomservice.DicomService/StreamSeriesThumbnails',
            dicom__service__pb2.SeriesQueryRequest.SerializeToString,
            dicom__service__pb2.SeriesThumbnailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudyThumbnails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/GetStudyThumbnails',
            dicom__service__pb2.StudyThumbnailsRequest.SerializeToString,
            dicom__service__pb2.StudyThumbnailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStudyDicomFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/GetStudyDicomFiles',
            dicom__service__pb2.StudyDicomRequest.SerializeToString,
            dicom__service__pb2.StudyDicomResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStudyDicomFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dicomservice.DicomService/StreamStudyDicomFiles',
            dicom__service__pb2.StudyDicomRequest.SerializeToString,
            dicom__service__pb2.DicomInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPatientList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dicomservice.DicomService/GetPatientList',
            dicom__service__pb2.PatientListRequest.SerializeToString,
            dicom__service__pb2.PatientListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
