from __future__ import annotations

# Validation / parsing
ERR_UNPARSED = "UNPARSED"
ERR_PLAN_VALIDATION_FAILED = "PLAN_VALIDATION_FAILED"
ERR_INVALID_ACTION = "INVALID_ACTION"
ERR_MISSING_FIELD = "MISSING_FIELD"
ERR_INVALID_TYPE = "INVALID_TYPE"
ERR_INVALID_VALUE = "INVALID_VALUE"
ERR_INVALID_ENTITY = "INVALID_ENTITY"
ERR_UNSUPPORTED_ENTITY = "UNSUPPORTED_ENTITY"

# Runtime
ERR_RUNTIME = "RUNTIME_ERROR"
