"""
Curved MPR View Window

This module provides a viewer window for displaying curved MPR images.
The window shows the straightened reformation image generated by CurvedMPRGenerator.

Features:
- Display curved MPR images
- Window/Level adjustment
- Zoom and pan controls
- Save capability
- Integration with main viewer

Author: AI Assistant
Created: 2025-11-30
"""

import vtk
from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLabel,
    QSlider, QMainWindow, QStatusBar
)
from PySide6.QtCore import Qt
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor


class CurvedMPRView(QMainWindow):
    """
    Window for displaying Curved MPR images.
    
    This window provides a dedicated viewer for curved MPR reformation images
    with basic interaction controls (window/level, zoom, pan).
    """
    
    def __init__(self, curved_mpr_image: vtk.vtkImageData, parent=None):
        """
        Initialize the Curved MPR viewer window.
        
        Args:
            curved_mpr_image: vtkImageData from CurvedMPRGenerator
            parent: Parent widget (optional)
        """
        super().__init__(parent)
        
        self.curved_mpr_image = curved_mpr_image
        self.viewer = None
        
        # Setup UI
        self._setup_ui()
        self._setup_viewer()
        
        print("[CurvedMPRView] Window initialized")
    
    def _setup_ui(self):
        """Setup the user interface"""
        self.setWindowTitle("Curved MPR View")
        self.setGeometry(100, 100, 800, 600)
        
        # Create central widget
        central_widget = QWidget()
        self.setCentralWidget(central_widget)
        
        # Main layout
        main_layout = QVBoxLayout(central_widget)
        main_layout.setContentsMargins(5, 5, 5, 5)
        
        # Title bar
        title_layout = QHBoxLayout()
        title_label = QLabel("Curved MPR Reformation")
        title_label.setStyleSheet("""
            QLabel {
                font-size: 16px;
                font-weight: bold;
                color: #2196F3;
                padding: 5px;
            }
        """)
        title_layout.addWidget(title_label)
        title_layout.addStretch()
        
        # Info label
        dims = self.curved_mpr_image.GetDimensions()
        self.info_label = QLabel(f"Size: {dims[0]}×{dims[1]} pixels")
        self.info_label.setStyleSheet("color: gray; padding: 5px;")
        title_layout.addWidget(self.info_label)
        
        main_layout.addLayout(title_layout)
        
        # VTK widget for display
        self.vtk_widget = QVTKRenderWindowInteractor(self)
        self.vtk_widget.setMinimumHeight(400)
        main_layout.addWidget(self.vtk_widget, stretch=1)
        
        # Control panel
        control_layout = self._create_control_panel()
        main_layout.addLayout(control_layout)
        
        # Status bar
        self.status_bar = QStatusBar()
        self.setStatusBar(self.status_bar)
        self.status_bar.showMessage("Curved MPR loaded successfully")
        
        # Apply dark theme styling
        self.setStyleSheet("""
            QMainWindow {
                background-color: #2b2b2b;
            }
            QWidget {
                background-color: #2b2b2b;
                color: #ffffff;
            }
            QPushButton {
                background-color: #3d3d3d;
                color: white;
                border: 1px solid #555;
                padding: 8px 16px;
                border-radius: 4px;
                font-size: 13px;
            }
            QPushButton:hover {
                background-color: #4d4d4d;
                border: 1px solid #2196F3;
            }
            QPushButton:pressed {
                background-color: #2196F3;
            }
            QSlider::groove:horizontal {
                border: 1px solid #555;
                height: 8px;
                background: #3d3d3d;
                border-radius: 4px;
            }
            QSlider::handle:horizontal {
                background: #2196F3;
                border: 1px solid #2196F3;
                width: 18px;
                margin: -5px 0;
                border-radius: 9px;
            }
        """)
    
    def _create_control_panel(self) -> QHBoxLayout:
        """Create the control panel with buttons and sliders"""
        control_layout = QHBoxLayout()
        control_layout.setSpacing(10)
        
        # Window/Level controls
        wl_layout = QVBoxLayout()
        
        # Window slider
        window_label = QLabel("Window:")
        window_label.setStyleSheet("font-size: 12px;")
        self.window_slider = QSlider(Qt.Horizontal)
        self.window_slider.setMinimum(1)
        self.window_slider.setMaximum(4000)
        self.window_slider.setValue(2000)
        self.window_slider.valueChanged.connect(self._on_window_changed)
        
        wl_layout.addWidget(window_label)
        wl_layout.addWidget(self.window_slider)
        
        # Level slider
        level_label = QLabel("Level:")
        level_label.setStyleSheet("font-size: 12px;")
        self.level_slider = QSlider(Qt.Horizontal)
        self.level_slider.setMinimum(-1000)
        self.level_slider.setMaximum(3000)
        self.level_slider.setValue(1000)
        self.level_slider.valueChanged.connect(self._on_level_changed)
        
        wl_layout.addWidget(level_label)
        wl_layout.addWidget(self.level_slider)
        
        control_layout.addLayout(wl_layout, stretch=1)
        
        # Buttons
        button_layout = QVBoxLayout()
        
        # Reset view button
        reset_btn = QPushButton("Reset View")
        reset_btn.clicked.connect(self._reset_view)
        button_layout.addWidget(reset_btn)
        
        # Save button
        save_btn = QPushButton("Save Image")
        save_btn.clicked.connect(self._save_image)
        button_layout.addWidget(save_btn)
        
        # Close button
        close_btn = QPushButton("Close")
        close_btn.clicked.connect(self.close)
        button_layout.addWidget(close_btn)
        
        control_layout.addLayout(button_layout)
        
        return control_layout
    
    def _setup_viewer(self):
        """Setup the VTK viewer for the curved MPR image"""
        # Create image viewer
        self.viewer = vtk.vtkImageViewer2()
        
        # Set render window
        render_window = self.vtk_widget.GetRenderWindow()
        self.viewer.SetRenderWindow(render_window)
        
        # Set interactor
        interactor = render_window.GetInteractor()
        self.viewer.SetupInteractor(interactor)
        
        # Set input image
        self.viewer.SetInputData(self.curved_mpr_image)
        
        # Configure viewer
        self.viewer.SetSliceOrientationToXY()  # 2D image
        self.viewer.SetSlice(0)
        
        # Get renderer
        renderer = self.viewer.GetRenderer()
        renderer.SetBackground(0.0, 0.0, 0.0)  # Black background
        
        # Setup window/level based on image data
        scalar_range = self.curved_mpr_image.GetScalarRange()
        print(f"[CurvedMPRView] Image scalar range: {scalar_range}")
        
        # Auto window/level
        window = scalar_range[1] - scalar_range[0]
        level = (scalar_range[1] + scalar_range[0]) / 2.0
        
        if window > 0:
            self.viewer.SetColorWindow(window)
            self.viewer.SetColorLevel(level)
            
            # Update sliders
            self.window_slider.setValue(int(window))
            self.level_slider.setValue(int(level))
        
        # Enable interaction
        style = vtk.vtkInteractorStyleImage()
        interactor.SetInteractorStyle(style)
        
        # Render
        self.viewer.Render()
        interactor.Initialize()
        
        # Fit image to window
        self._fit_to_window()
        
        print(f"[CurvedMPRView] Viewer setup complete")
    
    def _fit_to_window(self):
        """Fit the image to the window size"""
        renderer = self.viewer.GetRenderer()
        renderer.ResetCamera()
        
        # Get image dimensions
        dims = self.curved_mpr_image.GetDimensions()
        
        # Adjust camera for proper aspect ratio
        camera = renderer.GetActiveCamera()
        camera.ParallelProjectionOn()
        
        # Calculate scale to fit
        window_size = self.vtk_widget.size()
        if window_size.width() > 0 and window_size.height() > 0:
            x_scale = dims[0] / window_size.width()
            y_scale = dims[1] / window_size.height()
            scale = max(x_scale, y_scale) * 0.5
            
            camera.SetParallelScale(dims[1] * scale)
        
        self.viewer.Render()
    
    def _on_window_changed(self, value):
        """Handle window slider change"""
        if self.viewer:
            self.viewer.SetColorWindow(value)
            self.viewer.Render()
            self.status_bar.showMessage(f"Window: {value}, Level: {self.level_slider.value()}")
    
    def _on_level_changed(self, value):
        """Handle level slider change"""
        if self.viewer:
            self.viewer.SetColorLevel(value)
            self.viewer.Render()
            self.status_bar.showMessage(f"Window: {self.window_slider.value()}, Level: {value}")
    
    def _reset_view(self):
        """Reset the view to default"""
        # Reset window/level to auto
        scalar_range = self.curved_mpr_image.GetScalarRange()
        window = scalar_range[1] - scalar_range[0]
        level = (scalar_range[1] + scalar_range[0]) / 2.0
        
        if window > 0:
            self.viewer.SetColorWindow(window)
            self.viewer.SetColorLevel(level)
            self.window_slider.setValue(int(window))
            self.level_slider.setValue(int(level))
        
        # Reset camera
        self._fit_to_window()
        
        self.status_bar.showMessage("View reset")
        print("[CurvedMPRView] View reset")
    
    def _save_image(self):
        """Save the curved MPR image to file"""
        from PySide6.QtWidgets import QFileDialog
        
        # Ask user for filename
        filename, _ = QFileDialog.getSaveFileName(
            self,
            "Save Curved MPR Image",
            "curved_mpr.png",
            "PNG Image (*.png);;JPEG Image (*.jpg);;TIFF Image (*.tiff);;All Files (*)"
        )
        
        if filename:
            try:
                # Create window to image filter
                w2if = vtk.vtkWindowToImageFilter()
                w2if.SetInput(self.viewer.GetRenderWindow())
                w2if.Update()
                
                # Determine writer based on extension
                if filename.lower().endswith('.png'):
                    writer = vtk.vtkPNGWriter()
                elif filename.lower().endswith(('.jpg', '.jpeg')):
                    writer = vtk.vtkJPEGWriter()
                elif filename.lower().endswith(('.tif', '.tiff')):
                    writer = vtk.vtkTIFFWriter()
                else:
                    # Default to PNG
                    writer = vtk.vtkPNGWriter()
                    filename += '.png'
                
                writer.SetFileName(filename)
                writer.SetInputConnection(w2if.GetOutputPort())
                writer.Write()
                
                self.status_bar.showMessage(f"Image saved: {filename}")
                print(f"[CurvedMPRView] Image saved to: {filename}")
                
            except Exception as e:
                self.status_bar.showMessage(f"Error saving image: {e}")
                print(f"[CurvedMPRView] Error saving: {e}")
    
    def closeEvent(self, event):
        """Handle window close event"""
        print("[CurvedMPRView] Window closed")
        
        # Cleanup VTK resources
        if self.viewer:
            self.viewer.GetRenderWindow().Finalize()
        
        if hasattr(self, 'vtk_widget'):
            self.vtk_widget.Finalize()
        
        event.accept()
    
    def resizeEvent(self, event):
        """Handle window resize"""
        super().resizeEvent(event)
        if self.viewer:
            # Maintain aspect ratio on resize
            self.viewer.Render()


# Standalone function for easy integration
def show_curved_mpr(curved_mpr_image: vtk.vtkImageData, parent=None):
    """
    Show a curved MPR image in a new window.
    
    Args:
        curved_mpr_image: vtkImageData from CurvedMPRGenerator
        parent: Parent widget (optional)
    
    Returns:
        CurvedMPRView window instance
    """
    window = CurvedMPRView(curved_mpr_image, parent)
    window.show()
    return window

